server:
  port: 18082

spring:
  application:
    name: ypbin-system
  cloud:
    nacos:
      server-addr: ${NACOS_ADDR:localhost:8848}
  config:
    import:
      - optional:nacos:ypbin-common.yaml
      - optional:nacos:ypbin-system.yaml
