server:
  port: 18083

spring:
  application:
    name: ypbin-ai
  cloud:
    nacos:
      server-addr: ${NACOS_ADDR:localhost:8848}
  config:
    import:
      - optional:nacos:ypbin-common.yaml
      - optional:nacos:ypbin-ai.yaml
