server:
  port: 18081

spring:
  application:
    name: ypbin-auth
  cloud:
    nacos:
      server-addr: ${NACOS_ADDR:localhost:8848}
  config:
    import:
      - optional:nacos:ypbin-common.yaml
      - optional:nacos:ypbin-auth.yaml
