server:
  port: 18080

spring:
  application:
    name: ypbin-gateway
  cloud:
    nacos:
      server-addr: ${NACOS_ADDR:localhost:8848}
  config:
    import:
      - optional:nacos:ypbin-common.yaml
      - optional:nacos:ypbin-gateway.yaml
